import { getSession } from 'next-auth/react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { auth } from '@/auth';
import { MdDashboard } from "react-icons/md";
import Header from "@/component/global/header";
import SideNav from "@/component/global/side_nav";
import { Box } from '@mui/material';
import { ToastContainer, toast } from 'react-toastify';
import SessionProvider  from '@/context/session_context';
import 'react-toastify/dist/ReactToastify.css';
import {AbilityContextProvider} from '@/context/ability_context'
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const session=await auth()
  return (
    <html lang="en">

      <SessionProvider session={session}>

        <AbilityContextProvider>
        <Box component="body" sx={{display:'flex'}}>
         <SideNav/>
         <ToastContainer/>

         <Box sx={{display:'flex',flexDirection:'column',width:'80vw'}}>
         <Header/>
        {children}
         </Box>

        </Box>

        </AbilityContextProvider>
     

      </SessionProvider>
      
    </html>
  );
}
